# Generated by Django 3.1.6 on 2021-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_past', models.IntegerField()),
                ('customer', models.CharField(max_length=128)),
                ('milk', models.DecimalField(decimal_places=2, max_digits=20)),
                ('skins', models.IntegerField()),
            ],
        ),
    ]
