# Generated by Django 3.1.7 on 2021-02-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herd',
            fields=[
                ('days_past', models.IntegerField(primary_key=True, serialize=False)),
                ('yaks', models.JSONField(default=list)),
            ],
        ),
    ]
